src/Entity/Membre.php
<?php

namespace App\Entity;

use App\Repository\MembreRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * @ORM\Entity(repositoryClass=MembreRepository::class)
 */
class Membre implements UserInterface
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     */
    private $email;

    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     */
    private $password;

    /**
     * @ORM\Column(type="string", length=20, nullable=true)
     */
    private $pseudo;

    /**
     * @ORM\Column(type="string", length=50)
     */
    private $nom;

    /**
     * @ORM\Column(type="string", length=50)
     */
    private $prenom;

    /**
     * @ORM\Column(type="string", length=1)
     */
    private $civilite;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $adresse;

    /**
     * @ORM\Column(type="string", length=5)
     */
    private $code_postal;

    /**
     * @ORM\Column(type="string", length=50)
     */
    private $ville;

    /**
     * @ORM\OneToMany(targetEntity=Commande::class, mappedBy="membre", orphanRemoval=true)
     */
    private $commandes;

    public function __construct()
    {
        $this->commandes = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUsername(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getPassword(): string
    {
        return (string) $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getSalt()
    {
        // not needed when using the "bcrypt" algorithm in security.yaml
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getPseudo(): ?string
    {
        return $this->pseudo;
    }

    public function setPseudo(?string $pseudo): self
    {
        $this->pseudo = $pseudo;

        return $this;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->prenom;
    }

    public function setPrenom(string $prenom): self
    {
        $this->prenom = $prenom;

        return $this;
    }

    public function getCivilite(): ?string
    {
        return $this->civilite;
    }

    public function setCivilite(string $civilite): self
    {
        $this->civilite = $civilite;

        return $this;
    }

    public function getAdresse(): ?string
    {
        return $this->adresse;
    }

    public function setAdresse(string $adresse): self
    {
        $this->adresse = $adresse;

        return $this;
    }

    public function getCodePostal(): ?string
    {
        return $this->code_postal;
    }

    public function setCodePostal(string $code_postal): self
    {
        $this->code_postal = $code_postal;

        return $this;
    }

    public function getVille(): ?string
    {
        return $this->ville;
    }

    public function setVille(string $ville): self
    {
        $this->ville = $ville;

        return $this;
    }

    /**
     * @return Collection|Commande[]
     */
    public function getCommandes(): Collection
    {
        return $this->commandes;
    }

    public function addCommande(Commande $commande): self
    {
        if (!$this->commandes->contains($commande)) {
            $this->commandes[] = $commande;
            $commande->setMembre($this);
        }

        return $this;
    }

    public function removeCommande(Commande $commande): self
    {
        if ($this->commandes->contains($commande)) {
            $this->commandes->removeElement($commande);
            // set the owning side to null (unless already changed)
            if ($commande->getMembre() === $this) {
                $commande->setMembre(null);
            }
        }

        return $this;
    }
}

src/Entity/Test.php
<?php

namespace App\Entity;

use App\Repository\TestRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=TestRepository::class)
 */
class Test
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="datetime")
     */
    private $date_enregistrement;

    /**
     * @ORM\Column(type="string", length=50)
     */
    private $etat;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDateEnregistrement(): ?\DateTimeInterface
    {
        return $this->date_enregistrement;
    }

    public function setDateEnregistrement(\DateTimeInterface $date_enregistrement): self
    {
        $this->date_enregistrement = $date_enregistrement;

        return $this;
    }

    public function getEtat(): ?string
    {
        return $this->etat;
    }

    public function setEtat(string $etat): self
    {
        $this->etat = $etat;

        return $this;
    }
}

src/Controller/ProfilController.php
<?php

namespace App\Controller;

use App\Entity\Commande, App\Entity\Detail;
use App\Repository\ProduitRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\Session\SessionInterface as Session;
use Doctrine\ORM\EntityManagerInterface as EntityManager;

class ProfilController extends AbstractController
{
    /**
     * @Route("/profil", name="profil")
     */
    public function index()
    {
        // la méthode getUser renvoie un objet Membre contenant les informations de l'utilisateur connecté
        // $membre = $this->getUser();
        return $this->render('profil/index.html.twig');
    }

    /**
     * @Route("/commander", name="commander")
     */
    public function commander(Session $session, EntityManager $em, ProduitRepository $pr)
    {
        $panier = $session->get("panier");
        $cmd = new Commande;
        $cmd->setMembre($this->getUser());
        $cmd->setDateEnregistrement(new \DateTime("now"));
        $cmd->setEtat("en attente");
        $montant = 0;
        foreach($panier as $ligne){
            $montant += $ligne["produit"]->getPrix() * $ligne["quantite"];
            $detail = new Detail;
            $detail->setQuantite($ligne["quantite"]);    
            $detail->setPrix($ligne["produit"]->getPrix());
            // EXO : vérifier que la quantité commandée ne dépasse pas le stock
            //       sinon, réduire la quantité commandée (= stock)
            $prod = $pr->find($ligne["produit"]->getId());
            $prod->setStock( -$ligne["quantite"]);

            $detail->setProduit($prod);
            $detail->setCommande($cmd);
            $em->persist($detail);
        }
        $cmd->setMontant($montant);
        $em->persist($cmd);
        $em->flush();
        $session->remove("panier");
        return $this->redirectToRoute("profil");
    }

    /**
     * @Route("/profil/commande/{id}", name="profil_commande_detaille", methods={"GET"})
     */
    public function show(Commande $commande)
    {
        // EXO : vérifier que la commande que l'on veut afficher a été passé par le membre connecté
        //      sinon rediriger vers la page profil
        if( $this->getUser()->getId() == $commande->getMembre()->getId() ){
            return $this->render('commande/show.html.twig', [
                'commande' => $commande,
            ]);
        }
        $this->addFlash("danger", "Vous ne pouvez pas afficher cette commande");
        return $this->redirectToRoute("profil");
    }
}

templates/profil/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Profil Membre{% endblock %}

{# Dans un template twig, il y a une variable globale qui permet d'accéder à plusieurs informations concernant 
    le site : app
    Par exemple 
        app.user : utilisateur connecté
#}

{% block body %}
    <h1>Profil du membre {{ app.user.pseudo }}</h1>
    
    <div class="row">
        <div class="col-6">
            <table class="table">
                    <tbody>
                        <tr>
                            <th>Email</th>
                            <td>{{ app.user.email }}</td>
                        </tr>
                        <tr>
                            <th>Password</th>
                            <td>***</td>
                        </tr>
                        <tr>
                            <th>Pseudo</th>
                            <td>{{ app.user.pseudo }}</td>
                        </tr>
                        <tr>
                            <th>Nom</th>
                            <td>{{ app.user.nom }}</td>
                        </tr>
                        <tr>
                            <th>Prénom</th>
                            <td>{{ app.user.prenom }}</td>
                        </tr>
                        <tr>
                            <th>Civilité</th>
                            <td>{{ app.user.civilite }}</td>
                        </tr>
                        <tr>
                            <th>Adresse</th>
                            <td>{{ app.user.adresse }}</td>
                        </tr>                        
                        <tr>
                            <th>Code Postal</th>
                            <td>{{ app.user.codePostal }}</td>
                        </tr>
                        <tr>
                            <th>Ville</th>
                            <td>{{ app.user.ville }}</td>
                        </tr>
                    </tbody>
            </table>
                
        </div>

        <div class="col-6">
            <h2>Historique des commandes</h2>
            <table class="table">
                <thead>
                    <tr>
                        <th>Date</th>
                        <th>Montant</th>
                        <th>Etat</th>
                        <th>actions</th>
                    </tr>
                </thead>
                <tbody>
                {% for commande in app.user.commandes %}
                    <tr>
                        <td>{{ commande.dateEnregistrement ? commande.dateEnregistrement|date('d/m/y H:i:s') : '' }}</td>
                        <td>{{ commande.montant }}</td>
                        <td>{{ commande.etat }}</td>
                        <td>
                            <a href="{{ path('profil_commande_detaille', {'id': commande.id}) }}"><i class="fa fa-file"></i></a>
                        </td>
                    </tr>
                {% else %}
                    <tr>
                        <td colspan="5">Aucune commande</td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>

{% endblock %}